---
# Start of YAML file for Ansible Templating lab This is the file that you wrote

- hosts: all
  become: yes
  become_user: root
  vars:
    file_name: "hardened.j2"
    dest_dir: "/etc/sudoers.d/hardened"
  tasks:
    - name: create dir name
      file:
        path: /home/ansible/lab-templates
        state: directory
        mode: '0755'
      debug:
        msg: " created lab-templates dir"

    - name: deploy tempalte to dir
      template: 
        src: ./hardened.j2 
        dest: /etc/sudoers.d/hardened 
        mode: 755 
        validate: true
      debug:
        msg: " {{ file_name }} was deployed successfully to {{ dest_dir }}"

        