---
- hosts: all
  become: yes
  become_user: root
  vars:
    file_name: hardened.j2
    dest_dir: /etc/sudoers.d/hardened
  tasks:
    - name: Create directory for template deployment
      file:
        path: /home/ansible/lab-templates
        state: directory
        mode: 755
      # debug:
      #   msg: " created lab-templates dir"
    - name: deploy tempalte to dir
      template:
        src: ./hardened.j2
        dest: /etc/sudoers.d/hardened
        mode: 755
        validate: true
    - name: Show debug msg
      debug:
        msg: " {{ file_name }} was deployed successfully to {{ dest_dir }}"
